## Based on the travis-simple.yml (https://raw.githubusercontent.com/commercialhaskell/stack/stable/doc/travis-simple.yml)

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

env:
  global:
    - RACKET_VERSION=6.10
    - RACKET_DIR=~/racket

install:
  # Download and unpack the stack executable
  - echo "Installing Stack...\n"
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

  # Install Racket
  # Maybe we shouldn't depend on a GitHub repo. But I guess it's ok for v1
  - echo "Installing Racket...\n"
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

# We have a private submodule, and can't clone it without adding proper keys to Travis
git:
  submodules: false

script:
  ./run_all_tests.sh

notifications:
  email: false
  slack:
    secure: k1QQ6SgOB+JB2rX6KYTHm6xQoX45orQnq8eKEXRSa7xfyCfb1hlrZBV56MHWaAjm0sdZfsZorZBZO93+zD3a+i9pFfmQSRUhQfFDKyHXlhSFgQ185vAhM8WYTeAtvnkUCYvZx0yol2xEhswnEdfnRWe9ADxhZERenjbs4ZjiCsHthj3YMICPyX0ZuJS4KAPmWhpWQRS1/7fjXHAPNWgffDVn/35nbW6mXHNxb+tV+WyzoZue9/EJrnoi0DzLB5dT7BxIc0QZa1P4prM563lilsFdTj/BXeZyy6SrQYNNDwGZWDiVuqDTshlWwboPDjhd4mJqu39YzKG9Uzz/8QBm976zkKMy+1LkbR1KJqw+GkAkEA4l3soXBcRmjQdKTRaJG/pYT3s38TLRSw3w5Fw/mtWM8B7XIx2TN6WgMNIjRieMBTl0doQzQkhXXGmOGSty+/d2JYJTXzZpsCFtaWlWPqX5j79aVR9/KTyn6ItQpPCzZa1Wvw/oeNqEf6HNju9CYdX6dyNe2+gQ5yY0sh0wWKrJAs39E/ZDb5Ii1PO28rur3An3i9wyEfPvNfy0yo0lWJ+16HSVU1gMdpecm4RpT5781LCDT0pDg2FiHgNpwx04ihIQFz0w83drOfj50Q1EsFRatSdNtraprrcljaiLtc5/uI+tv+ldUDZtj+o+aA0=
