sudo: required

# Install some Nix tools.
# See https://docs.travis-ci.com/user/languages/nix.
language: nix

# Ubuntu 16.04.
dist: xenial

cache:
  directories:
  - $HOME/.stack

# TODO: after the Nix jobs start working on Travis we should look into
# caching Nix things too: https://nixos.wiki/wiki/Nix_on_Travis.

# Ensure necessary system libraries are present
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - hvr-ghc
    packages:
      - libgc-dev
      - libgmp-dev
      - uthash-dev
      - gcc-7
      - ghc-8.4.3

# Build in three modes, varying ONLY the environment used to build
# Docker code.
matrix:
  include:
    - name: default

    - name: stack_docker
      env: STACK_DOCKER=1

    # Travis fails with "No space left on device" while trying to install
    # Gibbon's dependencies (the Haskell ones, via Stack) :(
    - name: coarse_nix
      env: COARSE_NIX=1
      install: skip
      addons: skip
      script:
        - df -h
        - nix-shell shell.nix --run "COARSE_NIX=1 ./run_all_tests.sh"

    - name: stack_nix
      env: STACK_NIX=1

  # Temporary:
  allow_failures:
    - name: stack_docker
    - name: stack_nix

install:
  # Download and unpack the stack executable
  # The Ubuntu package is only available on >16.04. Travis is using 14.04.
  # Update: Travis supports Ubuntu 16.04 since Nov 2018. We should start
  # using that.
  - echo "Installing Stack...\n"
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

  # Install Racket
  # 'plt/racket' is not in Travis's safelist (https://github.com/travis-ci/apt-source-safelist)
  # and they're not accepting requests to add more things into it. Do this the old-fashioned way.
  - echo "Installing Racket...\n"
  - sudo add-apt-repository -y ppa:plt/racket
  - sudo apt-get update
  # The Racket package does not include version # in it's name.
  - sudo apt-get install -y racket
  - racket --version

  # Set up PATH for GHC.
  - export PATH=/opt/ghc/bin/:$PATH
  - ghc --version

  # GCC version hack.
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
  - gcc --version


# We have a private submodule, and can't clone it without adding proper keys to Travis
git:
  submodules: false

# Default.
script:
  ./run_all_tests.sh

branches:
  except:
  - parallel-local
  - parallel-local2

notifications:
  email: false
  slack:
    on_pull_requests: false
    on_success: change
    on_failure: always
    rooms:
      secure: W0V/gX0an9TL/I/Sseet9yLcwOvc7ZXA08QmzXDNQtJE/juHKPAI0zzMELWVzQ1W4qeil3vlPfrcA3zLsCJ2Ecco0+KN/XEvgKpE8McQ7h9WLCdk/laaASEx/bMGEKDPfUIgA/1vlI6AX+rr/5DpGW1o1IixqIRrxwE5yHmFUNUuAyMI82gU1Whv1pwxiKs6r9q/+9HnuQSJQa+OO8rEQa91zjFKshfh2tFdD1DhjVK5UUsZnMlV6C3btbVTfltO0sudzUST7kftAq3lRYYMRfRJbtKNtzDCbhiUp4bbAT7bRe34CkkIZcapyaSGcSDhK91XSd1vFDVynJSCF1yql9YP4uuaYEmzKx78iqiT/zhH2Cyu7Laxc5aoBI9TVaupeDpGJH/kcLDvCsBZU8PsHI2TUZiWc94rX4GA3cVpjfwlo+gNQutDfuDUa75WNQCSZzUWzpnFcMTftBuQYztpoeR+Y5+UaTSqZcVpSKaOxeRIknz4umIiUjCGug9CjqWqgbxL2cnFnWWJMxhcr+INBwiickSV+xSuqqE92ZIHA5ildA2Ett10yduN/wMBat9qOO0wlur7Nv6yLDNWfkYkD5IlWEbxgtfCbgbwOn/GtgTG7SfXpct1g2HtDcM1d2MPSczkzMJvFSt86uGOoiltcMwesnoQuyxifQhWWGRppXg=
