
# RRN: having problems with my ubuntu 6.10 laptop on 7.  Leaving this
# at lts 6 for now.  It shouldn't really matter either way.
resolver: lts-6.23
# resolver: lts-7.5
packages:
- '.'
extra-deps:
- s-cargot-0.1.1.1
# - tslogger-0.1.0.0
# - async-2.0.2
flags: {}
extra-package-dbs: []

# Temp, for tslogger above:
# allow-newer: true

docker:
  enable: false
  image: "fpco/stack-build:lts-6.23"
