
# RRN: having problems with my ubuntu 6.10 laptop on 7.  Leaving this
# at lts 6 for now.  It shouldn't really matter either way.
resolver: lts-6.23
# resolver: lts-7.5
packages:
- '.'
extra-deps: []
flags: {}
extra-package-dbs: []

docker:
  enable: false
  image: "fpco/stack-build:lts-6.23"
