# RRN: having problems with my ubuntu 6.10 laptop on LTS 7.  Leaving this
# at lts 6 for now.  It shouldn't really matter either way.
# resolver: lts-6.23
resolver: lts-9.0

packages:
- location:
    git: https://github.com/llvm-hs/llvm-hs
    commit: fcfbe26ca1a93a98891a4791b7c22cde74dfd369
  extra-dep: true
  subdirs:
    - llvm-general
    - llvm-general-pure
- location:
    git: https://github.com/aisamanra/s-cargot
    commit: eec500106f2c507ba3ffb4e9b025704103fb6dea
  extra-dep: true
- '.'

extra-deps:
- s-cargot-1.2.0.0
- llvm-general-pure-3.9.0.0
- llvm-general-3.9.0.0
- GenericPretty-1.2.1


flags: {}
extra-package-dbs: []


# Run with, e.g.:
#  NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-17.03.tar.gz
# If you want to pin things for reproducible builds
nix:
  enable: false
  packages: [gcc, which]
  # path: ["https://github.com/NixOS/nixpkgs-channels/archive/nixos-17.03.tar.gz"]
  # nixos-unstable snapshot:
  # path: ["nixpgs=https://github.com/NixOS/nixpkgs-channels/archive/1e1472ed93e1256dfdac4908ae8edcb90ceff21c.tar.gz"]
  # shell-file: shell.nix

system-ghc: true

docker:
  enable: false
  auto-pull: true
#  image: "fpco/stack-build:lts-6.23"
