resolver: nightly-2018-05-11

packages:
- '.'

extra-deps:
- s-cargot-0.1.4.0
- llvm-hs-5.1.3
- llvm-hs-pure-5.1.2
- haskell-src-exts-simple-1.20.0.0

flags: {}
extra-package-dbs: []


# Run with, e.g.:
#  NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-17.03.tar.gz
# If you want to pin things for reproducible builds
nix:
  enable: false
  packages: [gcc, which]
  # path: ["https://github.com/NixOS/nixpkgs-channels/archive/nixos-17.03.tar.gz"]
  # nixos-unstable snapshot:
  # path: ["nixpgs=https://github.com/NixOS/nixpkgs-channels/archive/1e1472ed93e1256dfdac4908ae8edcb90ceff21c.tar.gz"]
  # shell-file: shell.nix

system-ghc: true

docker:
  enable: false
  auto-pull: true
#  image: "fpco/stack-build:lts-6.23"
