
# RRN: having problems with my ubuntu 6.10 laptop on LTS 7.  Leaving this
# at lts 6 for now.  It shouldn't really matter either way.
resolver: lts-6.23
# resolver: lts-7.13
packages:
- location:
    git: https://github.com/llvm-hs/llvm-hs
    commit: fcfbe26ca1a93a98891a4791b7c22cde74dfd369
  extra-dep: true
  subdirs:
    - llvm-general
    - llvm-general-pure
- '.'

extra-deps:
- s-cargot-0.1.1.1
# - tslogger-0.1.0.0
# - async-2.0.2
- llvm-general-pure-3.9.0.0
- llvm-general-3.9.0.0

flags: {}
extra-package-dbs: []

# Temp, for tslogger above:
# allow-newer: true

docker:
  enable: false
  image: "fpco/stack-build:lts-6.23"
